#
# JobListings
# by refractored
#
Database:
  url: "jdbc:mysql://localhost:3306/database"
  user: "USERNAME"
  password: "PASSWORD"

Orders:
  # Max orders per rank coming soon
  MaxOrders: 3
  MaxOrdersAccepted: 3
  # Maximum/Minimum time in hours orders can be posted for
  MaxOrdersTime: 192
  MinOrdersTime: 48
  # Deadline in hours to complete an order
  OrderDeadline: 24

# Mail is used when an order is updated and the player is offline
Mail:
  # Mail Expire time in hours
  ExpireTime: 96